[package]
name = "mavsdk-bindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.6.0"
prost = "0.9.0"

[build-dependencies]
tonic-build = "0.6.0"
